"""auto-vote automatically add votes table

Revision ID: 546f47073bd3
Revises: cb65ecbd624c
Create Date: 2023-07-09 10:34:57.288222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546f47073bd3'
down_revision = 'cb65ecbd624c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
